export const PHOTOS = [
	{'image': 'adam', 'title': 'Adam at Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'hermiston', 'title': 'Hermiston', 'subtitle': 'Hermiston, Oregon'},
	{'image': 'walulla', 'title': 'Wallula Gap', 'subtitle': 'Wallula Gap, Washington'},
	{'image': 'lecole', 'title': 'L\'ecole 41', 'subtitle': 'Walla Walla, Washington'},
	{'image': 'mill-creek', 'title': 'Mill Creek', 'subtitle': 'Walla Walla, Washington'},
	{'image': 'mill-creek2', 'title': 'Mill Creek', 'subtitle': 'Walla Walla, Washington'},
	{'image': 'marcus-whitman2', 'title': 'Marcus Whitman Hotel & Conference Center', 'subtitle': 'Walla Walla, Washington'},
	{'image': 'walla-walla', 'title': 'Walla Walla', 'subtitle': 'Walla Walla, Washington'},
	{'image': 'walla-walla2', 'title': 'Walla Walla', 'subtitle': 'Walla Walla, Washington'},
	{'image': 'walla-walla3', 'title': 'Walla Walla', 'subtitle': 'Walla Walla, Washington'},
	{'image': 'marcy', 'title': 'Marcy\'s', 'subtitle': 'Walla Walla, Washington'},
	{'image': 'doubleback', 'title': 'Doubleback Winery', 'subtitle': 'Walla Walla, Washington'},
	{'image': 'night', 'title': 'Walla Walla', 'subtitle': 'Walla Walla, Washington'},
	{'image': 'night2', 'title': 'Walla Walla', 'subtitle': 'Walla Walla, Washington'},
	{'image': 'mill-creek3', 'title': 'Mill Creek', 'subtitle': 'Walla Walla, Washington'},		
	{'image': 'balloon', 'title': 'Balloon', 'subtitle': 'Walla Walla, Washington'},
	{'image': 'marcus-whitman3', 'title': 'Marcus Whitman Hotel & Conference Center', 'subtitle': 'Walla Walla, Washington'},
	{'image': 'castrol', 'title': 'Castrol Man', 'subtitle': 'Walla Walla, Washington'},
	{'image': 'waitsburg', 'title': 'Waitsburg', 'subtitle': 'Waitsburg, Washington'},
	{'image': 'waitsburg2', 'title': 'Waitsburg', 'subtitle': 'Waitsburg, Washington'},	
	{'image': 'warning', 'title': 'Warning, Brewery Ahead', 'subtitle': 'Waitsburg, Washington'},
	{'image': 'statue', 'title': 'Statue', 'subtitle': 'Waitsburg, Washington'},
	{'image': 'touchet', 'title': 'Touchet River', 'subtitle': 'Waitsburg, Washington'},
	{'image': 'hills', 'title': 'Palouse Hills', 'subtitle': 'Columbia County, Washington'},
	{'image': 'hills2', 'title': 'Palouse Hills', 'subtitle': 'Columbia County, Washington'},
	{'image': 'hills3', 'title': 'Palouse Hills', 'subtitle': 'Columbia County, Washington'},
	{'image': 'hills4', 'title': 'Palouse Hills', 'subtitle': 'Columbia County, Washington'},
	{'image': 'hills5', 'title': 'Palouse Hills', 'subtitle': 'Columbia County, Washington'},
	{'image': 'hills6', 'title': 'Palouse Hills', 'subtitle': 'Columbia County, Washington'},
	{'image': 'hills7', 'title': 'Palouse Hills', 'subtitle': 'Columbia County, Washington'},	
	{'image': 'dayton', 'title': 'Dayton', 'subtitle': 'Dayton, Washington'},
	{'image': 'snake', 'title': 'Snake River', 'subtitle': 'Pataha, Washington'},	
	{'image': 'snake-river2', 'title': 'Snake River', 'subtitle': 'Pataha, Washington'},
	{'image': 'snake-river3', 'title': 'Snake River', 'subtitle': 'Pataha, Washington'},
	{'image': 'bridge', 'title': 'Bridge', 'subtitle': 'Pataha, Washington'},
	{'image': 'palouse', 'title': 'Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse2', 'title': 'Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse3', 'title': 'Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse4', 'title': 'Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse5', 'title': 'Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse6', 'title': 'Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse7', 'title': 'Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse8', 'title': 'Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse9', 'title': 'Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse10', 'title': 'Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse11', 'title': 'Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse12', 'title': 'Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse13', 'title': 'Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse14', 'title': 'Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse15', 'title': 'Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},	
	{'image': 'palouse-river', 'title': 'Palouse River', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse-river2', 'title': 'Palouse River', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse-river3', 'title': 'Palouse River', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'palouse-river4', 'title': 'Palouse River', 'subtitle': 'Palouse Falls State Park, Washington'},	
	{'image': 'upper-palouse', 'title': 'Upper Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'upper-palouse2', 'title': 'Upper Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'upper-palouse3', 'title': 'Upper Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'upper-palouse4', 'title': 'Upper Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'train', 'title': 'Train', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'official', 'title': 'Official', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'adam2', 'title': 'Adam at Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},	
	{'image': 'adam3', 'title': 'Adam at Palouse Falls', 'subtitle': 'Palouse Falls State Park, Washington'},
	{'image': 'boardman', 'title': 'Boardman', 'subtitle': 'Boardman, Oregon'},	
	{'image': 'boardman2', 'title': 'Boardman', 'subtitle': 'Boardman, Oregon'},	
	{'image': 'boardman3', 'title': 'Boardman', 'subtitle': 'Boardman, Oregon'},	
]
