export const WHITMAN = 'After dinner, I walked around downtown to see some nighttime views, just as the sun was setting. But as I got to the statue of Marcus Whitman, my Mom called me just as I was about to press the button. As I talked to my Mom, I got the chance to appreciate surrounding area, from the tree behind it to the moon. In the end, after talking to Mom, I got the picture I wanted, incorporating all three elements in my picture. Hence, the anatomy of a 5 minute Picture.'

export const HOTPOOP = 'A music store located in Walla Walla, Hot Poop obviously stands out for its funny name. I walked inside just to check it out, but the store was cluttered and felt too much like a maze. I saw some Hot Poop shirts, but nothing I really liked. Otherwise, I didn\'t see anything to my liking. After a couple of minutes of not seeing anything, I walked out. But hey, I did check out Hot Poop. At least it\'s not cold.'

export const LOCATION = `
**Portland:** 211 miles  
**Seattle:** 217 miles  
**Spokane:** 119 miles  
**Boise:** 198 miles  
**Salt Lake City** 590 miles  
**Fort Collins:** 1000 miles  
**San Clemente**: 1089 miles  
**Washington D.C.:** 2075 miles    
`

export const WINGS = `
While I was walking through downtown Walla Walla, I decided to look for some dinner places. I admit I did some research beforehand, coming across a cool looking place called Wingman Birdz & Brewz. There were some other decent places I saw, but nothing stood out as a fun place like this place. So looking for an early dinner, ate my dinner here.

Inside, I found a fun sports-bar type atmosphere with lots of TV’s with NCAA tournament action and fun looking waiters and waitresses. Though this place looked like a good place to have a beer, I was craving a glass of wine, being in the heart of Walla Walla Wine Country. I settled for a favorite varietal, the Malbec from Oregon. It was quite delicious, a great selection on my behalf.

For dinner, I picked their standard item, chicken wings. I settled for 6 Boneless Wings with a side of French Fries. For the wings, I had the option of dipping it in a long variety of sauces. I couldn't decide on one I really wanted from a long list, so I picked the Carolina BBQ, with its mustard based BBQ. A questionable pair with the Malbec but I didn't care. The wings were quite delicious, they went down fairly quickly and savored every bite. The fries were plenty and good, seeing that I haven't had them in a while, but they weren't my favorite French Fries by any means.

Overall, I had a good experience at Wingman Birdz & Brewz. On the plus side, I had a good glass of wine and dinner. On the downside, the only NCAA basketball game I was able to see where I was sitting was Wisconsin vs. Pitt, which was the lowest scoring tournament game in about 15 years. Close game, but I couldn't get into it.
`

export const PALOUSE = `My trip to Palouse Falls was put it simply, amazing.  It started out heading out to Walla Walla, where I spent the night.  In the morning, after having some breakfast, I started my trip up to Palouse Falls State Park.  I immediately became impressed with the surrounding scenery.  Driving through the Palouse Hills was nothing like I've ever seen before.  Hill after hill of green and brown seemed out of this world to me.  I stopped in the town of Waitsburg, which to me seemed like a charming old western type town.  With a bill Palouse hill with the Waitsburg water tower, you could immediately tell where you were.  And with a warning sign indicating brewery ahead, you could tell it was modern as well.  As I left Waitsburg, I continued my way up to Palouse Falls, where more windy and turns roads took me through the hills.  Eventually, I reached water, as suddenly I was side by side the Snake River.  Naturally I had to stop to take a couple of pictures.  Then things started to become real interesting, as the elevation suddenly went up, and the surrounding area became more rugged and diverse.  Things were really crazy when I crossed a bridge, with views of another incredibly tall bridge nearby.  It looked freaky.

Finally I made it to Palouse Falls, where the real fun began.  Thankfully for me, today is Washington State Park’s 103rd Birthday; as such, I didn't have to pay a $10 dollar fee to get in.  It would have be worth the 10 dollars, but still, thanks Washington.  The first thing that struck me about Palouse Falls was how tall it was; a deep plunge down the Palouse River, a tributary off the Snake River.  As I looked down the canyon to view the falls, I was amazed by how deep and wide the canyon was.  Not quite the Grand Canyon but still impressive.  And with such a sunny day, I was set for fun.  True, I told Jenn I wouldn't go near any cliffs or see any waterfalls (the last request seems odd to me; Jenn has never told me not to see a waterfall).  But like a mature adult, I kept my distance and didn't do anything stupid or risky.  Looking afar from one of the viewpoints of Palouse Falls, another gentlemen pointed out someone right at the falls, which I told the man was crazy to do.  I stuck with the viewpoints up above; they were still amazing.  

I walked around the area, around the edges but not too far away, continuing to find viewpoints of the River which were great to see.  Finally, I reached another waterfall, the upper Palouse Falls.  Though not too tall and not particularly interesting, I still took plenty of pictures of the area, as I love to do.  It was so nice to see all the beautiful viewpoints, as unofficial as they are.  I would hope official trails are made, marked for those looking to be careful and feel safe.  Having warning signs is helpful, but also make it seem more scary than it needs to be.  I follow the rules of common sense; don't stand on the edge of a cliff and make sure your foot is at least the distance of your foot away.  Not 12 inches, but the length of your foot away.

I spent an hour and a half here.  Fortunately, I had my iPhone charger on me as my iPhone kept using up battery.  I took little breaks to charge my phone and write the first half of this post while I was doing so.  It was both convenient and relaxing, allowing me to gather my thoughts while keeping my phone charged.  Either way, time well spent.  I didn't get the perfect setting that I had hoped for, but I still managed to get plenty of amazing pictures, with my experience, and that's still better than nothing.
`

export const BOARDMAN = 'Boardman, Oregon, enough to make you bored man in Oregon. For some reason, my sister felt it was important to tell my Dad I went there twice, based on my Swarm check-in\'s. Of course, I only stopped there once on the way back. Heading out there, I made a restroom stop near Boardman. I remember going to the rest stop there once remembering it to be the most disgusting bathroom I had ever been in. This time I was pleasantly surprised; it even had a modern sink. Coming back the other direction, I stopped to stretch and walked around a park along the Columbia River for a few minutes. Peaceful enough to remind me why small towns are enjoyable in the right situation, yet not the type of place I would want to live in. Arlington was more interesting when I walked around there a couple of years back. There are way too many industrial plants outside of Boardman, which reminds me too much of Millersburg, Oregon with all the stinky plants along I-5. All in all, it was worth it to stretch out. I even saw a bunch of birds dive into the Columbia River all at once. That was a worthy event. But it\'s not worth visiting twice, sorry Jenn.'

export const ALL_MARKDOWN = [WHITMAN, LOCATION, HOTPOOP, WINGS, PALOUSE, BOARDMAN]
